sudo: required
services:
          - docker

language: node_js
node_js:
        - "iojs"
        - "8"

before_script:
        - npm install -g @angular/cli
        - npm install -g karma
        - npm install
        - ng build

script: karma start config/karma.conf.js --single-run


env:
        matrix:
        - SERVICE=angular
        - SERVICE=express
