sudo: required
services:
- docker
language: node_js
node_js:
- '8'
notifications:
  email: false
env:
    secure: "TXfwFktkHRsKAdwgM5l3+3+chATNA3sJlgeW0yeY79aiLbb5nOv8+JOYckLgp3/l+epWRU9A7lO0ztO769IEdQh1Bcj9t9BfnP3NWerbjRuUvE9XhTBCZgxo8beYzXqC5HntLg2X6ee+Y25J/Kif8NObflSi+hWZLan6vURdXEjnIBCh5Er6BzW1O1TtjgwkZEuiefFMcn6UTqfAXTNhjTzSSC9wyjZW+PCioFdDhT1HLlhHWopEMOLmb5KSi+fyJLvQ8/2hdidE6gqHwLYpH3lHmJ1XqbOd13IvVUhej4jzBaRubqIXpb2vaxYF1VC8XTgyGyFfaIvHSytkG61rqUsu1VOIx14wToZdVTwtwg2qeut2jS+uuVi2wNQj1sJ8Wd4ZKNX2g5ubXI0SeYaymRsE+sd54WhFnnPoiEeA+qLf4+I3WsetKXpKemMGMk6k5ATD6HxWzzEYuLdEcxBBhfdRBqPKIaE4eftj3D6UYeaVJtfATEDyxvQip8gVn9UA/Ewfqt7wH2iTKWzZxoB/v+bda39od6JtIbdR5pL4N0iuIm4Ejn26UuNffdjLeATzo6cB5RQxdMbyaGPwL5XQOGYK592dgfgc9nrpPxwXTesw8GHadP8v/qqeCYSnh5CNRvRX/yArIMPusKvH0tT1Fagnx6gzuzHe+GGWTB43PcY="