sudo: required
services:
- docker
language: node_js
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
node_js:
  - '8'
cache:
        directories:
                - node_modules
                - public
notifications:
  email: false
env:
  global:
    - secure: Q0gegCvStydo4RwR3WhJc9b13YmFmIuUHMi8oXCF/W82Cpgy0YO3M8emi/J3W8ErOCITRiWak2lApfJhsdAphR/n6O6z4QloGU2/ERUDq/CW2DOBBBe6LTfeyafBsRwq+fNeFOswN+8Kj+j+5GKiFbOgD8sfVLIssP2M+T46apruSXMjhTP/nyKlhDZR7tC4wBPOpdcvrLinFuk6syHy/0LswC9AGWuBBhb3Fvl4TNlSr6j47Xwp0Py7hn02paRq43NuLScgRG7nTbJSgGbk6hrAJLp+cFGkRdlYuzymvu1AJ86rkFqIqYMcF1iPuwKOR+f3KNxj6cqAbdLgDKycaoktAIppPSc06hdB6PR6vNfXwqR8Sc7y4ARZcqAxa0Lc6jzPFQbroyrF848YOHYcQ9zv8rn6O/KCEQL2xesF+vUnh1ci5MVnZK5oPgao5Uis2pdxIyJ4WbITgx3R0ED+46WaF15a9I8ivGUMhjTmcCtLjvmSwMHFK+bHIroAd/76sXeQyhPBLZBceFuqSVHZ3F9kEmfhw9XTXcK+Qn4RT+tNA2SFrA6N1bSSIsTd7nx8ETe10lUd9RvzSSrPcSLzDgJ3mNJn6z5FRzAPDBSEEyKIN3JwT30AOpimcX5alAvOKOJtKFRSUw4+Te/5dbGUECp9ruOX26x92wXM0IeVfPg=
    - secure: qyugG0w+XP97vdPL8Gbg7zkF0y5VI7e10DHE7QUaIlnCj+PYOtFnbdQf1V+m1tTQoRXknd1Fc0jDRH4g7ESLaGVFHdctZfe9QxlLpFonhMstVbhrWpRl+lZC5U7Y1yN22r6WYYpHC0p8uqlDPXXrahUMu+ou4WV3hArwx/ES0bilyAq+/R6f5gVoVBBanXXWUyaBUbWwcdcxLqF5iT3dBHYnFGrHecbw3jPr8FvmXVRssJZL4pWatuE7iHWEJyRzQfQi4uwL4O5pusCfWHXD98n1n9IQ7QxEC+m7A15NoPZfUK0f+GO3W8t9tdh7jn/eywmQVkYJyu9oQy6nhRFW69/vpmj54EwVAag28Klh/emOcsXI4pV0y0ZuVm2Cmyd57aPecPQvpgguB68ssDkp4w38THJnLwB1xEHD4NaqX0wP064jEVcDTgdomsdnans8T7snGnGaAYTlOxQ45GFrFp86v5efTLwhAzqPVBBjxbtYg+efWuiw7RgUg3PHAJ/Xhl21zU+cGz4ztQLjDiJzBBuFDfDjxkNGjG1soTjMZT1JixqmEPgbUdiX/V7GRzYT1IGWUXu2GW1uMbiieIHeWJJ8Zof0xH98d9XO99nvO2OWPKcGuMnlTBe1qbPNqa3RaQgStk/8tHvQZIi8Ahj829nuLyYSAxlV049lRiPmaDE=
