sudo: required
services:
- docker
language: node_js
node_js:
- '8'
notifications:
  email: false
env:
  secure: gf1bC/OLcoXRZkEl3+iF4BxzIImE6XmcluHUhUK2wQuz9kS/t800DyEUmnDFcKkq6sqkKRExuzjIyUN7cq4WPEEqcc+l8RQdYTsXqj9kizeYCwjSWKJQXKogFYQ7i/y722rTDasb+Uj7BIwUXeV7ecOz8c/HE9cbG25UjuIZdZVXteZuUefAVPsszWrGUN/8IR19VfoPdtSwc5/SHgUUlNFP/ScGC91VWsWYbX7IvS3Ci+kVLXO2xsEyl14DbXm5IYIAV30o4cwGM4sPKORKdmGeCNgTpBafZhgrjnYyo5tm2XsCplcYMsFtBpzOAF32zIRiKfBxfD+7d6W+MpGME+MjddtOO21FQJscCXiXa/J8Dyn+C+Q1CSzoDJ69py5wSc+dId6aMV5Fwg/1F2ga+qVqkr44wVequ8g99ElsqO2C0ASdwMWsq41FK5lSmLmv18FX+Znlo5sf8sDzaZTbSBeIhS+6sw5FOu3WTkYwCOu6bwCD8Ubh2ZyIt87jOOhCu3gRcGujHIxIZmC/NNLS+xnR7DMdE80Z156PPI3FrjUxElZfX/JxThdyj9y2wtnIg2NN0MNyQdvR/VV8Yh9kzGV7UN7PkwMnYk0+Gxj0CKHcS8svhXJH75tjpjYcNnjpFqq8aOTkOphYSmwvAow5jP2DH4BJYiq6G5KtT0ab9Nk=
