sudo: required
services:
- docker
language: node_js
node_js:
- '8'
notifications:
  email: false
env:
  secure: RWdUr62ZE8kAAXwpzx682xQ8L60VBy3GGH2OOZVSTy5ElhIDA8AXXv3hQ1lGHZ/I7RHbSIiM6u8dbutEBfQVst3WCmhhQSQpetM4fv+WJCbmFSeiKS25jk7pNwWzaPB7w23+3hb38oH3hIOVP1SXLy7ozY8LAee//lyRyzTpgQ+qAWl/atCSjlKy411kXI+R+yD3CsboeJdKf89gbe8e4z74jfvlOMTG/8aIe6x3Q1au3KCHaDxnj3HtNzzNPP9tj8alW8YWs5xgLBk/Lruop12enPR/yTLut4HonDIofy/RPY5+G45bgeGbXMeiXLWP2NID1Xso128OaQPZWpdIxzAgKOWaBrCCxF0Y6aNsk+5nxMYiYULgeAtLWcM67lWcXh2QtFz4f44tFBQUDqdkYTnjFAMZ/SYuLs2eNFQ0t9eubP4ouM/fTwmIyJCBTLvBVvNz+9sdHA6ciBNrOwEDKmrTiuhqYt1vaUFRM0ACEmWBVV3SZ/gLah1ZZyWRsoUMp1HXgOPg0/tWDejHFRT7f25Lg81iIFoT5nL3AZ9N+YgA+ss1w/Qnprncl9LwvjVHzaz3tTq1Yfe8de3oWBjeTcjaR4vqx33GiLaJGbIu335Usug+6+qk9h64xjbUTIfYEJQRhg6JOzaJZy1u3OKlw7Q2bmOmWTowKVY55oslF3A=
