sudo: required
services:
- docker
language: node_js
node_js:
- '8'
notifications:
  email: false
env:
    secure: "dBZwKnjzeAR0r98VfpIO+6fYepJSm3nATsN/x9m8cbHtCx59YII1hcWyS3P86e0+s5+cUjfpDRDFIz8zrFGpGsRtOp4P+GdKnZI5lILX0YfCx9+dsBROiLtwfvfIFPAW/dvde4Lqfy3zj2EQ/QdIhXiEfLyFitf/rZa6aCp5e3w18DGlDlv7+cf4vROfRwSkqQWf2vvICt259rnidN/AGrcKWVwanQovYyhercVzJifhABlPlXOAuLJU8GNVtR7Ky/Qj+IGrr8atb7XleJozYfFORUiHNUcmpgxlxbT+D8g8K6ghnCFZXajjIrZglN4stvfHUsq/HkTEXFcorjKaFqXjU4145CRm/6Sf9rwv88y9SDKDxehfpz11Qa3XJAsIgWOa6QiL59aW6AMlF3VMheQWGr861ViOi6d7Ursfw/sm8aC0V9MGsC3vCxu5I9c+/nlGcvbC/Cwyvx6AlnzLE9J9I5Yetwr/fxeC00HfVDlPVh1fHc7tvUsig0Z4heonCJOblOapl9Zuwz9av1g8L3nxnJEmjEMjcc0z9RgUNOKklC7DkCR1dWiSRD/IuOC3p6XX6LT7AYzTa8V4Yvoru6q90LR5uLlINZwFUIczOo0NWjyCJnby37N6uBaWWRUlPrgP7mvk+EVIKo+Lhr4/BAa9Pd+bDeTaBRT4mvLnOvg="
