sudo: required
services:
          - docker

language: node_js
node_js:
        - "iojs"
        - "8"

cache:
directories:
        - "node_modules"
env:
        matrix:
        - SERVICE=angular-client
        - SERVICE=express-server
