sudo: required
services:
- docker
language: node_js
node_js:
- '8'
notifications:
  email: false
env:
  secure: OLVUuGq8WEQiRJQl3qsyKxrPFiEDy/ESyh29BOm6178dkCvmRUQlaAIq65F6+ESP3rMT3X8zE7uNkAsxZ+9Yyepda7iwxBFF5ZHpi7dN4QtWxDm+OAnhvUHVFPeZnyUHwhC7bvRYGPqnnYDiNVi/TwiYZy39sEINjojDDlq4E/SVYDQdHC1C8b7eZhgBpsrOnkZmr7+KgV3WLnxUsgBUl8pqjDbwlV9FNEsYIqMoI4K6g/TJxTM7fpMfnl5aCyC9IvvVCbllzrkk9xxi46Mib33pTFXzYw9Jb78hCb76o8ZGXNe8VaCoiHEPPXwymYX2JU0IWxNOZ7sRchgB7sGml+Zfl+c8SaIHb9v2XNKzydEyShvevsKnVfQgrOZN+XA9zXIhG5WCIYwVkWCiHGvD8PEbwSiGB+yyYnglcI4I91mJO3yXIaMLkQgQvnKqukU5MwdK29s7KV1CWHH0M16vvMruKOYHiZD52k0N/xG0EbmXalNyy8PjWzTLRwgj/vQ/JIdEixWVT2ePoSV7yOjDrhdGLnDLvHo9zplhgxdVLSG7cQ3KexW0RvFfztaTrsPSiySLFx/j89sS6OLNNAMOyAhSkscYfheDuR2W24v126e97knGqhfBjXvcqjh0DCxr1gH/cyHjcARZGJEHeNfIQODtdBgtVaGDrzu/tvkvF5o=
